### ISSUE TITLE
Multiple services of type EventDispatcherInterface found

### ISSUE THREAD

**Issue by juniwalk** [Zenify/DoctrineMigrations#29]
When migrations are registered after kdyby/doctrine in `config.neon` I get following error when CLI command is executed:

```
[2016-10-11 08-39-51] Nette\DI\ServiceCreationException: Multiple services of type Symfony\Component\EventDispatcher\EventDispatcherInterface found: events.symfonyProxy, 1.eventDispatcher in ./sandbox/vendor/nette/di/src/DI/ContainerBuilder.php:237  @  CLI (PID: 58812): www/index.php migrations:status  @@  exception--2016-10-11--08-39--dbe0e62d39.html
```

**Comment by enumag** [comment]
https://github.com/Arachne/EventDispatcher/blob/master/docs/index.md#troubleshooting

**Comment by juniwalk** [comment]
@enumag Hello, I get the error when I actually register arachne/event-dispatcher after kdyby/events. I've just tried it in other nette app and there it works both ways, before and after kdyby/doctrine extensions.

Should I post this issue to [Arachne/EventDispatcher](https://github.com/Arachne/EventDispatcher) repository?

**Comment by enumag** [comment]
@juniwalk Is EventDispatcherExtension _directly_ after EventsExtension? Do you have the latest version of arachne/event-dispatcher (v0.1.2)? If so then open an issue on Arachne/EventDispatcher repository.

According to my testing the problem should only occur in this case: https://github.com/Arachne/EventDispatcher/issues/1#issuecomment-250894993

**Comment by enumag** [comment]
@juniwalk Any progress?

**Comment by juniwalk** [comment]
@enumag Sorry I forgot. This is how I had it in config.

```yaml
extensions:
	# Doctrine Database
	translation: Kdyby\Translation\DI\TranslationExtension
	console: Kdyby\Console\DI\ConsoleExtension
	events: Kdyby\Events\DI\EventsExtension
	annotations: Kdyby\Annotations\DI\AnnotationsExtension
	doctrine: Kdyby\Doctrine\DI\OrmExtension

	# Doctrine Migrations
	- Arachne\ContainerAdapter\DI\ContainerAdapterExtension
	- Arachne\EventDispatcher\DI\EventDispatcherExtension
	migrations: Zenify\DoctrineMigrations\DI\MigrationsExtension
```
